#!/bin/bash


service mosquitto start

# Allow any signal which would kill a process to stop server
trap "service mosquitto stop" HUP INT QUIT ABRT ALRM TERM TSTP

while pgrep -u mosquitto mosquitto > /dev/null; do sleep 5; done
